name: 'Slack Notification'
description: 'Send notifications to Slack'
inputs:
  slack-webhook:
    description: 'Slack webhook URL'
    required: true
  slack-username:
    description: 'Username to display in the message'
    required: true
  slack-channel:
    description: 'Slack channel to post the message'
    required: true
  title:
    description: 'Message title'
    required: true
  text:
    description: 'Message text'
    required: true
  color:
    description: 'Color of the message'
    required: false
    default: 'good'

runs:
  using: composite
  steps:
    - name: Notify Slack Channel
      shell: bash
      run: |
        curl "${{ inputs.slack-webhook }}" -X POST -H "Content-Type: application/json" \
          --data '{
            "username": "${{ inputs.slack-username }}",
            "channel": "${{ inputs.slack-channel }}", 
            "attachments": [
            {
                "title": "${{ inputs.title }}",
                "text": "${{ inputs.text }}",
                "color": "${{ inputs.color }}"
              }
            ]
          }'
